#!/bin/bash

echo 'How old are you?'

read age

if [ $age -gt 20 ]
then
    echo 'You can drink.'
else
    echo 'You are too young to drink.'
fi

basename="testinging opa "
array=(45 4 4 7 8 8) 
for file in "${array[@]}"
do
  echo "${basename} ${file}"
done
